# Generated by Django 5.0.6 on 2024-06-01 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_code', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_target', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.line')),
            ],
        ),
        migrations.CreateModel(
            name='daily_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.PositiveIntegerField(default=0)),
                ('h2', models.PositiveIntegerField(default=0)),
                ('h3', models.PositiveIntegerField(default=0)),
                ('h4', models.PositiveIntegerField(default=0)),
                ('h5', models.PositiveIntegerField(default=0)),
                ('h6', models.PositiveIntegerField(default=0)),
                ('h7', models.PositiveIntegerField(default=0)),
                ('h8', models.PositiveIntegerField(default=0)),
                ('h9', models.PositiveIntegerField(default=0)),
                ('h10', models.PositiveIntegerField(default=0)),
                ('h11', models.PositiveIntegerField(default=0)),
                ('h12', models.PositiveIntegerField(default=0)),
                ('target_qty', models.PositiveIntegerField(default=0)),
                ('target_per', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.line')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.operator')),
            ],
        ),
    ]
