# Generated by Django 5.0.6 on 2024-06-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
