# Generated by Django 5.0.6 on 2024-06-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_operator_burmese'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
