# Generated by Django 5.0.6 on 2024-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_operatortargetrep_hourlytargetrep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlytargetrep',
            name='optname',
        ),
        migrations.AddField(
            model_name='hourlytargetrep',
            name='optname',
            field=models.ManyToManyField(to='myapp.operatortargetrep'),
        ),
    ]
