# Generated by Django 5.0.6 on 2024-06-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_hourlytargetrep_optname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatortargetrep',
            options={'ordering': ('id',)},
        ),
    ]
