# Generated by Django 5.0.6 on 2024-06-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_operatortargetrep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlytargetrep',
            name='optname',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.operatortargetrep'),
        ),
    ]
