# Generated by Django 5.0.6 on 2024-06-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_opreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opreport',
            old_name='cart',
            new_name='operatortargetrep',
        ),
    ]
