# Generated by Django 5.0.6 on 2024-06-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_cart_opreport_operatortargetrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='combine',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
