# Generated by Django 5.0.6 on 2024-06-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_daily_report_combine'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
