# Generated by Django 5.0.6 on 2024-06-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_daily_report_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='resign',
            field=models.BooleanField(default=False),
        ),
    ]
