# Generated by Django 5.0.6 on 2024-06-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_operator_resign'),
    ]

    operations = [
        migrations.CreateModel(
            name='licencedate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_date', models.DateField()),
            ],
        ),
    ]
