# Generated by Django 5.0.6 on 2024-06-13 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_point_created_date_point_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatortargetrep',
            name='operatorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyreport', to='myapp.operator'),
        ),
    ]
