# Generated by Django 5.0.6 on 2024-06-13 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_operatortargetrep_operatorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatortargetrep',
            name='operatorname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyreport', to='myapp.operator'),
        ),
    ]
