# Generated by Django 5.0.6 on 2024-06-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_operatortargetrep_operatorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='absant',
            field=models.BooleanField(default=False),
        ),
    ]
