# Generated by Django 5.0.6 on 2024-07-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_daily_report_absant'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
