# Generated by Django 5.0.6 on 2024-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_daily_report_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
