# Generated by Django 5.0.6 on 2024-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_daily_report_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyhour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timehr', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
