# Generated by Django 5.0.6 on 2024-07-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_dailyhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='hourcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
