# Generated by Django 5.0.6 on 2024-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_daily_report_hourcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='srno',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operator',
            name='srno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
