# Generated by Django 5.0.6 on 2024-07-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_daily_report_srno_operator_srno'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
