# Generated by Django 4.1.7 on 2024-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_daily_report_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='workinghr',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
