# Generated by Django 4.1.7 on 2024-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_ferry'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='redcolor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='successcolor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
