# Generated by Django 4.1.7 on 2024-09-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_line_redcolor_line_successcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='redcolor',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='daily_report',
            name='successcolor',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
